-- AlterTable: Replace classesBallon String[] with dedicated boolean fields for BFCL classes, groups, and qualifications

ALTER TABLE "pilote" DROP COLUMN IF EXISTS "classesBallon";

ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "classeA" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "classeB" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "classeC" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "classeD" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "groupeA1" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "groupeA2" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "groupeA3" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "groupeA4" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "qualificationNuit" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "qualificationInstructeur" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "pilote" ADD COLUMN IF NOT EXISTS "qualificationCaptif" BOOLEAN NOT NULL DEFAULT false;
